package service

import (
	"os"
	"path/filepath"
	"strings"
)

const runtimeProjectAgentsFileName = "AGENTS.md"
const codexsessManagedAgentsEndMarker = "<!-- /CODEXSESS -->"

func codexsessManagedAgentsBlock() string {
	return strings.TrimSpace(strings.Join([]string{
		"<!-- CODEXSESS:START -->",
		"<!-- AUTOGENERATED: CodexSess managed block. Update/replace only this block. -->",
		"",
		"## CodexSess Session Rules",
		"",
		"- This workspace is used by CodexSess /chat sessions.",
		"- Follow the CodexSess superpowers workflow when the task needs design or multi-step implementation planning.",
		"- Prefer native skill execution over backend-authored compatibility shims.",
		"",
		codexsessManagedAgentsEndMarker,
	}, "\n"))
}

func ensureCodingProjectAgentsFile(workDir string) error {
	root := strings.TrimSpace(workDir)
	if root == "" {
		return nil
	}
	path := filepath.Join(root, runtimeProjectAgentsFileName)
	raw, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	if strings.Contains(string(raw), codexsessManagedAgentsEndMarker) {
		return nil
	}
	block := codexsessManagedAgentsBlock() + "\n"
	if os.IsNotExist(err) || len(raw) == 0 {
		return os.WriteFile(path, []byte(block), 0o644)
	}
	body := block + "\n" + strings.TrimLeft(string(raw), "\n")
	return os.WriteFile(path, []byte(body), 0o644)
}
